package:
  name: asn1crypto
  version: '0.24.0'
source:
  url: https://files.pythonhosted.org/packages/fc/f1/8db7daa71f414ddabfa056c4ef792e1461ff655c2ae2928a2b675bfed6b4/asn1crypto-0.24.0.tar.gz
test:
  imports:
  - asn1crypto